/* SafeStart · หน้าจอฝั่ง SCG + รายละเอียดงาน (views_s.js) */

/* ---------- รายละเอียดงาน (ใช้ทั้งสองฝั่ง) ---------- */
function JobSheet({id}){useStore();const j=byId(S.jobs,id);if(!j)return null;const p=projOf(j.project_id);const pm=permitOf(id);const ci=ciOf(id);const co=ci&&closeOf(ci.id);const w=useWeather([j])[id];
  const hist=S.checkins.filter(c=>c.job_id===id).sort((a,b)=>b.work_date.localeCompare(a.work_date));const fs=jobFindings(id);const hc=ci?S.health.filter(h=>h.checkin_id===ci.id):[];
  const canDecide=pm&&pm.status==='pending'&&canApproveJob(j);const stopOK=isSCG()&&canStop()&&myCos().includes(j.scg_company_id);const a=j.site_answers||{};
  return html`<${Sheet} size="wide" title=${jtNames(j)+' · '+(j.house_no||'–')} sub=${(p?.name||'')+' · '+j.po_no+' · '+ctrName(j.contractor_id)}
    foot=${isContractor()?html`<div className="row" style=${{width:'100%'}}>${jobActions(j)}</div>`:stopOK?html`<div className="row" style=${{width:'100%'}}>
      ${j.status==='stopped'?html`<${Btn} kind="go" onClick=${()=>act(()=>rpc('resume_job',{p_job:id,p_note:'ปลดล็อกหลังตรวจแก้ไข'}),'ให้ทำงานต่อได้แล้ว')}>ปลดล็อกให้ทำงานต่อ</${Btn}>`:html`<${Btn} kind="red" icon="alert" onClick=${()=>UI.open(html`<${StopSheet} id=${id}/>`,'สั่งหยุดงาน')}>สั่งหยุดงาน</${Btn}>`}
      ${isSafety()?html`<${Btn} icon="flag" onClick=${()=>UI.open(html`<${LsrSheet} job=${id}/>`,'บันทึกโทษ LSR')}>บันทึกโทษ LSR</${Btn}>`:null}
      ${p_nav(j)?html`<a className="btn" href=${p_nav(j)} target="_blank" rel="noopener"><${Ic} n="map"/>แผนที่</a>`:null}</div>`:null}>
    <div className="row"><${CoBadge} id=${j.scg_company_id}/><${StateChip} j=${j}/><${Chip} c=${RISK[j.risk][0]} t=${RISK[j.risk][1]}/><${HzIcons} h=${j.hazards}/></div>
    ${j.status==='stopped'?html`<${Banner} kind="stop">หยุดงาน: ${j.stop_reason}</${Banner}>`:null}
    ${w&&(j.hazards||[]).includes('wah')&&w.level!=='ok'?html`<div className=${'wx '+w.level}><span className="ic-circle"><${Ic} n=${WXL[w.level][1]}/></span><div className="grow"><b>${WXL[w.level][2]}</b><div className="sm">${w.text}</div></div></div>`:null}
    <dl className="kv">
      <dt>ช่วงวันทำงาน</dt><dd>${thD(j.start_date)} – ${thD(j.end_date)} · นัด ${String(j.start_time).slice(0,5)} น.</dd>
      <dt>กลุ่มงาน</dt><dd>${grpName(p?.group_id)}</dd>
      <dt>IC</dt><dd>${profName(p?.ic_id)}${p?.backup_ic_id?' (สำรอง '+profName(p.backup_ic_id)+')':''}</dd>
      <dt>ผู้รับเหมา / ทีม</dt><dd>${ctrName(j.contractor_id)} · ${j.team_id?teamOf(j.team_id)?.name+' · '+profName(teamOf(j.team_id)?.lead_id):'ยังไม่เลือกทีม'}</dd>
      <dt>หน้างาน</dt><dd>${[a.height18&&'สูง ≥ 1.8 ม.',a.ladder&&'บันได',a.scaffold&&'นั่งร้าน',a.confined&&'ในฝ้า',j.occupied&&'มีผู้อยู่อาศัย',a.asbestos&&'อาจมีใยหิน'].filter(Boolean).join(' · ')||'–'}</dd>
      ${(j.hazards||[]).includes('wah')?html`<dt>จุดยึด</dt><dd>${a.anchor==='existing'?'มีจุดยึดเดิม':a.anchor==='install'?'ติดตั้งใหม่ · '+(j.setup_method||'')+' · '+(j.setup_worker_ids||[]).map(workerName).join(', '):'–'}</dd>`:null}
      <dt>แผนฉุกเฉิน</dt><dd>1669 · ${p?.hospital||'ยังไม่ตั้งค่าโรงพยาบาล'}${p?.hospital_phone?' · '+p.hospital_phone:''}</dd>
    </dl>
    <div className="card pad col tight"><div className="between"><b>ใบอนุญาตทำงาน</b>${pm?html`<${Chip} c=${pm.status==='approved'?'go':pm.status==='pending'?'warn':'stop'} t=${RISK[pm.tier][1]+' · '+(pm.status==='approved'?'อนุมัติแล้ว':pm.status==='pending'?'รออนุมัติ':'ตีกลับ')}/>`:html`<${Chip} t="ยังไม่ยื่น"/>`}</div>
      ${pm?html`<div className="xs muted">ยื่นโดย ${profName(pm.submitted_by)} ${thT(pm.submitted_at)}${pm.late?' · ยื่นช้ากว่ากำหนด':''}${pm.decided_at?' · อนุมัติ/ตัดสินโดย '+profName(pm.decided_by)+' '+thT(pm.decided_at):''}${pm.note?' · '+pm.note:''}</div>`:null}
      ${canDecide?html`<${DecidePermit} pm=${pm}/>`:null}</div>
    ${ci?html`<div className="card pad col tight"><div className="between"><b>Check-in วันนี้ ${hm(ci.created_at)}${ci.late?' (สาย)':''}</b>${co?html`<${Chip} c="info" t=${'ปิดงาน '+hm(co.created_at)}/>`:html`<${Btn} small=${true} kind=${ci.stage==='setup'?'orange':''} icon="qr" onClick=${()=>UI.open(html`<${PassSheet} token=${ci.pass_token}/>`,'บัตรผ่าน')}>${ci.stage==='setup'?'บัตรส้ม':'บัตรผ่าน'}</${Btn}>`}</div>
      <div className="sm">${ci.worker_ids.map(x=>workerName(x)+((ci.wah_worker_ids||[]).includes(x)?' (ขึ้นที่สูง)':'')).join(', ')}</div>
      <div className="xs muted">${ci.distance_m!=null?'ห่างจากบ้าน '+ci.distance_m+' ม.':''}${ci.out_of_radius_reason?' · เหตุผล: '+ci.out_of_radius_reason:''}${ci.toolbox_topic?' · Toolbox: '+ci.toolbox_topic:''}${ci.weather_choice==='ground_only'?' · อากาศ: ทำเฉพาะงานพื้น':''}${ci.setup_done_at?' · ส่งรูปจุดยึด '+hm(ci.setup_done_at):''}</div>
      <div className="row"><${Img} path=${ci.photos?.team}/><${Img} path=${ci.photos?.site}/>${Object.values(ci.setup_photos||{}).map(x=>html`<${Img} key=${x} path=${x}/>`)}${co?(co.photos?.after||[]).map(x=>html`<${Img} key=${x} path=${x}/>`):null}</div>
      ${hc.length?html`<div className="xs muted">ตรวจสุขภาพ (เห็นเฉพาะผู้ดูแลบริษัท/Safety): ${hc.map(h=>workerName(h.worker_id)+' '+h.pulse+' · '+h.sys+'/'+h.dia+' · '+h.alcohol+(h.pass?' ✓':' ✕')+(h.retest?' (วัดซ้ำ)':'')).join(' | ')}</div>`:null}
      ${co?.damage?html`<${Banner} kind="stop">แจ้งความเสียหาย: ${co.damage_note}</${Banner}>`:null}</div>`:null}
    ${fs.length?html`<${Card}><${CardH} icon="flag" title="Findings"/><div className="list">${fs.map(f=>html`<${FindingRow} key=${f.id} f=${f}/>`)}</div></${Card}>`:null}
    ${hist.length>1?html`<${Card}><${CardH} icon="history" title="ประวัติรายวัน"/><div className="card-b col tight">${hist.map(c=>{const x=closeOf(c.id);return html`<div key=${c.id} className="between sm"><span>${thD(c.work_date)} · check-in ${hm(c.created_at)}${c.late?' (สาย)':''}${c.voided?' · ยกเลิก: '+c.void_reason:''}</span><span className="muted">${x?'ปิดงาน '+hm(x.created_at)+(x.final?' · จบงาน':''):'ยังไม่ปิดงาน'}</span></div>`})}</div></${Card}>`:null}
  </${Sheet}>`}
function DecidePermit({pm}){const [note,setNote]=useState('');const j=byId(S.jobs,pm.job_id);const a=j.site_answers||{};
  return html`<div className="col tight"><div className="sm">คำถามหน้างาน: ${PLAN_Q.map(([k,t])=>html`<span key=${k} className=${'qa-tag '+(a[k]?'y':'n')}>${a[k]?'✓':'✗'} ${t.split(' (')[0]}</span>`)}</div>
    <div className="sm">ทีม: ${teamOf(j.team_id)?.name||'–'} · ${teamWorkers(j.team_id).map(w=>{const b=workerBlockers(workerOf(w),j.scg_company_id,j.hazards,j.start_date,(j.hazards||[]).includes('wah'));return workerName(w)+(b.length?' ⚠ '+b[0]:'')}).join(', ')}</div>
    <${Txt} v=${note} set=${setNote} ph="หมายเหตุ (ต้องใส่ถ้าตีกลับ)"/><div className="row"><${Btn} kind="danger" onClick=${()=>act(()=>rpc('decide_permit',{p_permit:pm.id,p_approve:false,p_note:note}),'ตีกลับแล้ว')}>ตีกลับ</${Btn}><${Btn} kind="go" onClick=${()=>act(()=>rpc('decide_permit',{p_permit:pm.id,p_approve:true,p_note:note||null}),'อนุมัติแล้ว')}>อนุมัติ</${Btn}></div></div>`}
function StopSheet({id}){const j=byId(S.jobs,id);const [r,setR]=useState('');const [lsr,setLsr]=useState('');const [ph,setPh]=useState(null);const L=sett('lsr',j.scg_company_id)||[];
  return html`<${Sheet} title="สั่งหยุดงาน" sub=${j.po_no+' · '+ctrName(j.contractor_id)} foot=${html`<${Btn} kind="red" block=${true} disabled=${!r.trim()} onClick=${async()=>{if(await act(()=>rpc('stop_job',{p_job:id,p_reason:r,p_lsr_rule:lsr?+lsr:null,p_photo:ph}),'สั่งหยุดงานแล้ว แจ้งผู้รับเหมาทันที')){UI.close()}}}>ยืนยันหยุดงาน</${Btn}>`}>
    <${Field} label="ฝ่าฝืนกฎพิทักษ์ชีวิตข้อไหน (ถ้ามี)"><${Sel} v=${lsr} set=${setLsr} opts=${[['','ไม่ใช่ LSR (ข้อบกพร่องวิกฤตอื่น)'],...L.map((t,i)=>[String(i+1),'ข้อ '+(i+1)+' '+t])]}/></${Field}>
    <${Field} label="สิ่งที่พบ"><${Txt} v=${r} set=${setR}/></${Field}><${Upload} label="รูปหลักฐาน" camera=${true} folder="scg" stamp=${['หยุดงาน PO '+j.po_no]} value=${ph} onChange=${setPh}/>
    <${Banner} kind="info">ทีมถูกล็อก check-in ไม่ได้จนกว่าจะปลดล็อก · ถ้าเป็น LSR ให้ Safety บันทึกโทษต่อ (เคสสอบสวนร่วม 10 วันอยู่รอบถัดไป)</${Banner}></${Sheet}>`}
function LsrSheet({job,worker}){useStore();const j=job&&byId(S.jobs,job);const co=j?j.scg_company_id:S.co;const [w,setW]=useState(worker||'');const [rule,setRule]=useState('');const [note,setNote]=useState('');const [res,setRes]=useState(null);const L=sett('lsr',co)||[];
  const ws=j?(ciOf(j.id)?.worker_ids||teamWorkers(j.team_id)):S.workers.map(x=>x.id);
  return html`<${Sheet} title="บันทึกโทษฝ่าฝืนกฎพิทักษ์ชีวิต" sub=${coName(co)+' · ระบบนับขั้นจากประวัติ 12 เดือน'} foot=${res?null:html`<${Btn} kind="red" block=${true} disabled=${!rule} onClick=${async()=>{const r=await act(()=>rpc('record_lsr',{p_co:co,p_worker:w||null,p_contractor:j?j.contractor_id:null,p_job:job||null,p_rule:+rule,p_kind:null,p_note:note}));if(r)setRes(r)}}>บันทึกโทษ</${Btn}>`}>
    ${res?html`<${Banner} kind="stop"><b>ขั้นที่ ${res.step}: ${res.penalty}</b><div className="sm">มีผลเฉพาะ ${coName(co)} · บริษัทอื่นในกลุ่มเห็น Flag แจ้งให้ทราบ · ผู้ดูแลบริษัทผู้รับเหมาได้รับแจ้งแล้ว</div></${Banner}>`:html`
    <${Field} label="ช่างที่ฝ่าฝืน (เว้นว่าง = โทษระดับบริษัท)"><${Sel} v=${w} set=${setW} opts=${[['','ระดับบริษัท'],...ws.map(x=>[x,workerName(x)])]}/></${Field}>
    <${Field} label="กฎข้อที่"><${Sel} v=${rule} set=${setRule} opts=${[['','เลือก'],...L.map((t,i)=>[String(i+1),'ข้อ '+(i+1)+' '+t])]}/></${Field}>
    <${Field} label="รายละเอียด"><${Txt} v=${note} set=${setNote}/></${Field}>
    <div className="sm muted">บุคคล Working Safety: ครั้งที่ 1 ห้ามทำงาน 7 วัน · ครั้งที่ 2 ตลอดชีพ · Driving: 3 วัน → 7 วัน → ตลอดชีพ · บริษัท: หนังสือแจ้ง + ปรับตามขั้น</div>`}</${Sheet}>`}

/* ---------- กระดานวันนี้ ---------- */
function SBoard(){useStore();const [f,setF]=useState({grp:'',ctr:'',st:''});
  let js=visJobs().filter(j=>isToday(j)&&j.status!=='cancelled');
  js=js.filter(j=>{const p=projOf(j.project_id);return(!f.grp||p?.group_id===f.grp)&&(!f.ctr||j.contractor_id===f.ctr)});
  const w=useWeather(js);
  let st=js.map(j=>[j,jobState(j)]).sort((a,b)=>a[1][2]-b[1][2]);if(f.st)st=st.filter(([,s])=>s[0]===f.st);
  const n=k=>js.filter(j=>jobState(j)[0]===k).length;const ci=js.filter(j=>ciOf(j.id)).length;const wxBad=js.filter(j=>(j.hazards||[]).includes('wah')&&w[j.id]&&['warn','stop'].includes(w[j.id].level)).length;
  const tiles=[['งานวันนี้',js.length,'','cal',''],['Check-in แล้ว',ci,'go','check',''],['ต้องดู',n('warn'),'warn','warn','warn'],['หยุด/วิกฤต',n('stop'),'stop','alert','stop'],['อากาศเสี่ยง (ที่สูง)',wxBad,wxBad?'warn':'','storm','']];
  return html`<div className="col">
    <div className="kpis">${tiles.map(([l,v,c,ic,k])=>html`<button key=${l} className=${cx('kpi',c,f.st===k&&k&&'on')} onClick=${()=>k&&setF(o=>({...o,st:o.st===k?'':k}))}><span className="ic-circle mute"><${Ic} n=${ic}/></span><div><div className="v num">${v}</div><div className="l">${l}</div></div></button>`)}</div>
    <div className="row filters"><${Sel} label="กลุ่มงาน" v=${f.grp} set=${v=>setF(o=>({...o,grp:v}))} opts=${[['','ทุกกลุ่มงาน'],...S.groups.filter(g4=>inCo(g4.scg_company_id)).map(x=>[x.id,x.name])]}/><${Sel} label="ผู้รับเหมา" v=${f.ctr} set=${v=>setF(o=>({...o,ctr:v}))} opts=${[['','ทุกผู้รับเหมา'],...S.contractors.map(x=>[x.id,x.name])]}/>
      ${canScan()?html`<${Btn} icon="scan" onClick=${()=>UI.go('scan')}>สแกนบัตรผ่าน</${Btn}>`:null}</div>
    <div className="board"><div className="card mapcard"><${BoardMap} items=${st} wx=${w}/></div>
      <div className="col tight boardlist">${st.length?st.map(([j,s])=>html`<button key=${j.id} className="card pad click brow" onClick=${()=>UI.open(html`<${JobSheet} id=${j.id}/>`,j.po_no)}>
        <span className=${'sdot '+s[0]}></span><div className="grow"><div style=${{fontWeight:600}}>${jtNames(j)} · ${j.house_no||'–'}</div><div className="xs muted">${projOf(j.project_id)?.name||''} · ${ctrName(j.contractor_id)} · นัด ${String(j.start_time).slice(0,5)}</div>
        <div className="row" style=${{gap:4,marginTop:4}}><${HzIcons} h=${j.hazards} size=${13}/>${(j.hazards||[]).includes('wah')&&w[j.id]&&w[j.id].level!=='ok'?html`<${WxChip} w=${w[j.id]}/>`:null}</div></div>
        <div className="col tight" style=${{justifyItems:'end'}}>${j.risk==='high'?html`<${Chip} c="stop" t="เสี่ยงสูง"/>`:null}<${Chip} c=${s[0]} t=${s[1]} dot=${true}/></div></button>`):html`<${Empty} icon="map" t="วันนี้ไม่มีงานในตัวกรองนี้"/>`}</div></div>
    <div className="legend sm muted"><span><i style=${{background:'var(--muted)'}}></i>รอ</span><span><i style=${{background:'var(--go)'}}></i>กำลังทำ</span><span><i style=${{background:'var(--warn)'}}></i>ต้องดู/บัตรส้ม</span><span><i style=${{background:'var(--stop)'}}></i>หยุด/วิกฤต</span><span><i style=${{background:'var(--info)'}}></i>ปิดแล้ว</span><span>ขอบหนา = เสี่ยงสูง · ⛈ = อากาศเสี่ยง</span></div></div>`}
function BoardMap({items,wx}){const ref=useRef(null);const mp=useRef(null);const lay=useRef(null);
  useEffect(()=>{let alive=true;loadScript('https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js','L').then(L=>{if(!alive||mp.current)return;
    mp.current=L.map(ref.current,{zoomControl:true}).setView([13.75,100.55],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(mp.current);lay.current=L.layerGroup().addTo(mp.current);draw()}).catch(()=>{});return()=>{alive=false}},[]);
  const col={go:'#16825D',warn:'#C46A00',stop:'#CF3A2F',info:'#2B63D9',mute:'#8D9AAD'};
  const draw=()=>{const L=window.L;if(!L||!lay.current)return;lay.current.clearLayers();const pts=[];
    items.forEach(([j,s])=>{if(j.lat==null)return;pts.push([j.lat,j.lng]);const bad=wx&&wx[j.id]&&['warn','stop'].includes(wx[j.id].level)&&(j.hazards||[]).includes('wah');
      L.circleMarker([j.lat,j.lng],{radius:j.risk==='high'?11:8,color:S.co==='all'?coColor(j.scg_company_id):j.risk==='high'?'#0E1726':'#fff',weight:j.risk==='high'?4:2,fillColor:col[s[0]],fillOpacity:.95})
      .bindTooltip(`${bad?'⛈ ':''}${j.house_no||''} · ${s[1]}`).on('click',()=>UI.open(html`<${JobSheet} id=${j.id}/>`,j.po_no)).addTo(lay.current)});
    if(pts.length)mp.current.fitBounds(pts,{padding:[30,30],maxZoom:15})};
  useEffect(draw,[items.map(([j,s])=>j.id+s[1]).join(),JSON.stringify(Object.keys(wx||{}))]);
  return html`<div ref=${ref} className="map" aria-label="แผนที่งานวันนี้"></div>`}

/* ---------- กล่องงาน ---------- */
function SInbox(){useStore();const co=S.co;
  const pms=S.permits.filter(pm=>{if(pm.status!=='pending')return false;const j=byId(S.jobs,pm.job_id);return j&&inCo(j.scg_company_id)&&canApproveJob(j)});
  const wl=canApproveWorkers()?S.wlinks.filter(l=>l.status==='pending'&&inCo(l.scg_company_id)):[];
  const cs=canApproveWorkers()&&co&&co!=='all'?S.certs.filter(c=>S.wlinks.some(l=>l.worker_id===c.worker_id&&l.scg_company_id===co&&l.status!=='rejected')&&!S.creviews.some(r=>r.cert_id===c.id&&r.scg_company_id===co)):[];
  const sd=isSafety()?S.workers.filter(x=>x.selfdec_status==='doctor_submitted'):[];
  const fx=S.findings.filter(f=>f.status==='fixed'&&inCo(f.scg_company_id));const inc=S.incidents.filter(i=>i.status==='new'&&inCo(i.scg_company_id));
  const setupLate=S.checkins.filter(c=>c.stage==='setup'&&!c.voided&&c.work_date===today()&&new Date(c.setup_due)<new Date()).map(c=>byId(S.jobs,c.job_id)).filter(j=>j&&inCo(j.scg_company_id));
  const un=S.notifs.filter(n=>n.need_ack&&!n.ack_at);const ctrP=S.links.filter(l=>l.status==='pending'&&inCo(l.scg_company_id)&&['purchasing','safety_admin'].includes(ME.role));
  const Box=({title,icon,n,children})=>html`<${Card}><${CardH} icon=${icon} title=${title} right=${html`<${Chip} c=${n?'warn':'go'} t=${n}/>`}/>${n?html`<div className="list">${children}</div>`:html`<div className="card-b sm muted">ไม่มี</div>`}</${Card}>`;
  return html`<div className="col"><div className="g2">
    <${Box} title="รออนุมัติใบอนุญาตเสี่ยงสูง" icon="flag" n=${pms.length}>${pms.map(pm=>{const j=byId(S.jobs,pm.job_id);return html`<button key=${pm.id} className="li" onClick=${()=>UI.open(html`<${JobSheet} id=${j.id}/>`,j.po_no)}><div className="grow"><div className="t">${j.po_no} · ${jtNames(j)} · ${j.house_no||''}</div><div className="s">${projOf(j.project_id)?.name||''} · ${ctrName(j.contractor_id)} · เริ่ม ${thDS(j.start_date)}${pm.late?' · ยื่นช้า':''}</div><${HzIcons} h=${j.hazards} size=${13}/></div><${Ic} n="chev"/></button>`})}</${Box}>
    <${Box} title="บัตรส้มเกิน 60 นาที" icon="clock" n=${setupLate.length}>${setupLate.map(j=>html`<button key=${j.id} className="li" onClick=${()=>UI.open(html`<${JobSheet} id=${j.id}/>`,j.po_no)}><div className="grow"><div className="t">${j.po_no} · ${j.house_no||''}</div><div className="s">${ctrName(j.contractor_id)} · ยังไม่ส่งรูปจุดยึด/ทางเดิน</div></div><${Chip} c="stop" t="เกินเวลา"/></button>`)}</${Box}>
    <${Box} title="แจ้งเหตุใหม่" icon="warn" n=${inc.length}>${inc.map(i=>html`<${IncidentRow} key=${i.id} i=${i}/>`)}</${Box}>
    ${canApproveWorkers()?html`<${Box} title="คำขอให้ช่างเข้าทำงาน" icon="id" n=${wl.length}>${wl.map(l=>{const x=workerOf(l.worker_id);if(!x)return null;const fl=S.flags.filter(f=>f.worker_id===x.id).length;return html`<button key=${l.worker_id+l.scg_company_id} className="li" onClick=${()=>UI.open(html`<${WorkerSheet} id=${x.id}/>`,x.full_name)}><div className="grow"><div className="t">${x.full_name} · ${x.position||''}</div><div className="s">${ctrName(x.contractor_id)} · ${coShort(l.scg_company_id)}</div></div>${fl?html`<${Chip} c="stop" t=${'Flag LSR '+fl}/>`:null}${x.id_verified_at?html`<${Chip} c="go" t="ตรวจบัตรแล้ว"/>`:html`<${Chip} c="warn" t="ต้องตรวจบัตร"/>`}${approvalMissing(x,l.scg_company_id).filter(i=>i.t!=='ตรวจตัวบุคคล').map(i=>html`<${Chip} key=${i.t} c="warn" t=${'ขาด '+i.t}/>`)}</button>`})}</${Box}>
      <${Box} title="cert / ผลตรวจสุขภาพ รอรับรอง" icon="doc" n=${cs.length}>${cs.map(c=>html`<button key=${c.id} className="li" onClick=${()=>UI.open(html`<${WorkerSheet} id=${c.worker_id}/>`,workerName(c.worker_id))}><div className="grow"><div className="t">${workerName(c.worker_id)}</div><div className="s">${certName(c.cert_type)}</div></div><${Chip} c="warn" t="รอรับรอง"/></button>`)}</${Box}>`:null}
    ${ctrP.length?html`<${Box} title="บริษัทผู้รับเหมารออนุมัติ" icon="building" n=${ctrP.length}>${ctrP.map(l=>html`<button key=${l.contractor_id} className="li" onClick=${()=>UI.open(html`<${CompanySheet} id=${l.contractor_id}/>`,ctrName(l.contractor_id))}><div className="grow"><div className="t">${ctrName(l.contractor_id)}</div><div className="s">${coShort(l.scg_company_id)}</div></div><${Ic} n="chev"/></button>`)}</${Box}>`:null}
    ${isSafety()?html`<${Box} title="ใบรับรองแพทย์ (Self-declaration) รอรับรอง" icon="heart" n=${sd.length}>${sd.map(x=>html`<button key=${x.id} className="li" onClick=${()=>UI.open(html`<${WorkerSheet} id=${x.id}/>`,x.full_name)}><div className="grow"><div className="t">${x.full_name}</div><div className="s">${ctrName(x.contractor_id)}</div></div><${Chip} c="warn" t="รอรับรอง"/></button>`)}</${Box}>`:null}
    <${Box} title="ผู้รับเหมาแจ้งแก้แล้ว รอตรวจรับ" icon="ok" n=${fx.length}>${fx.map(f=>html`<${FindingRow} key=${f.id} f=${f}/>`)}</${Box}>
    <${Box} title="แจ้งเตือนของฉันที่รอรับทราบ" icon="bell" n=${un.length}><div className="card-b col tight">${un.map(n=>html`<${NotifRow} key=${n.id} n=${n}/>`)}</div></${Box}>
  </div></div>`}
function WorkerReview({w,co}){useStore();const l=linkOf(w.id,co);const miss=approvalMissing(w,co);const [idn,setId]=useState('');const [note,setNote]=useState('');const [dup,setDup]=useState(null);const fl=S.flags.filter(f=>f.worker_id===w.id);
  if(!myCos().includes(co))return null;
  return html`<div className="col tight">
    ${!w.id_verified_at?html`${w.id_image_path?html`<${Img} path=${w.id_image_path} bucket="idcheck" cls="thumb lg" alt="รูปบัตรชั่วคราว"/>`:html`<div className="sm muted">ยังไม่มีรูปบัตร ตรวจจากบัตรตัวจริงที่หน้างานได้</div>`}
      <div className="row"><${Inp} v=${idn} set=${setId} ph="เลขบัตร 13 หลัก / เลขบัตรชมพู / Passport" mode=${w.nationality==='th'?'numeric':'text'}/>
      <${Btn} kind="dark" disabled=${idn.replace(/\D/g,'').length<8&&idn.length<8} onClick=${()=>act(async()=>{const r=await rpc('verify_worker_id',{p_worker:w.id,p_idno:idn,p_co:co});if(w.id_image_path)await sb.storage.from('idcheck').remove([w.id_image_path]);setDup(r);setId('')},'ตรวจแล้ว · เก็บเลขท้าย 4 หลัก · ลบรูปบัตรแล้ว')}>ยืนยันตัวบุคคล</${Btn}></div>
      <div className="xs muted">ระบบเก็บเฉพาะเลขท้าย 4 หลัก และรหัสทางเดียว (hash) ไว้ตรวจซ้ำการลงทะเบียน · ไม่มีใครอ่านเลขเต็มได้</div>`:null}
    ${dup&&dup.duplicates&&dup.duplicates.length?html`<${Banner} kind="stop"><b>เลขบัตรนี้ลงทะเบียนอยู่แล้ว</b>${dup.duplicates.map((d,i)=>html`<div key=${i} className="sm">${d.worker} · ${d.contractor}${d.flags.length?' · Flag LSR: '+d.flags.map(f=>'ข้อ '+f.rule+' '+f.penalty+' ('+f.company+')').join(', '):''}</div>`)}</${Banner}>`:null}
    ${fl.length?html`<${Banner} kind="stop"><b>Flag กฎพิทักษ์ชีวิต (แจ้งให้ทราบ · บริษัทตัดสินใจเอง)</b>${fl.map(f=>html`<div key=${f.id} className="sm">ข้อ ${f.rule} · ${thD(f.occurred_on)} · ${f.penalty} · ${coName(f.scg_company_id)}</div>`)}</${Banner}>`:null}
    ${l&&l.status==='pending'?html`<${Txt} v=${note} set=${setNote} ph="หมายเหตุ (ต้องใส่ถ้าไม่อนุมัติ)"/><div className="row"><${Btn} kind="danger" onClick=${()=>act(()=>rpc('decide_worker',{p_co:co,p_worker:w.id,p_approve:false,p_note:note}),'บันทึกแล้ว')}>ไม่อนุมัติ</${Btn}>
      <${Btn} kind="go" disabled=${miss.length>0} onClick=${()=>act(()=>rpc('decide_worker',{p_co:co,p_worker:w.id,p_approve:true,p_note:note||null}),'อนุมัติช่างแล้ว')}>อนุมัติให้เข้าทำงาน ${coShort(co)}</${Btn}></div>
      ${miss.length?html`<div className="xs" style=${{color:'var(--stop)'}}>ยังอนุมัติไม่ได้ · ขาด ${miss.map(x=>x.t).join(', ')} (ดูรายการคุณสมบัติด้านบน)</div>`:null}`:null}
    ${isSafety()?html`<${Btn} small=${true} kind="danger" icon="flag" onClick=${()=>UI.open(html`<${LsrSheet} worker=${w.id}/>`,'บันทึกโทษ LSR')}>บันทึกโทษ LSR</${Btn}>`:null}</div>`}

/* ---------- แผนงาน + นำเข้า PO (จับคู่คอลัมน์) ---------- */
const XLSX_URL='https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js';
function guessMap(headers,fields,saved){const m={};const norm=s=>String(s).toLowerCase().replace(/[\s_.()/-]/g,'');
  fields.forEach(([k,l])=>{const sv=saved&&saved[k];if(sv&&headers.includes(sv)){m[k]=sv;return}
    const keys=[k,l,...({po_no:['po','เลขที่po','ponumber','purchaseorder'],project:['หมู่บ้าน','โครงการ','project','site'],contractor:['vendor','ผู้รับเหมา','supplier','รหัสvendor'],job_types:['ประเภทงาน','งาน','service','item'],start_date:['วันเริ่ม','startdate','วันที่ติดตั้ง','installdate'],end_date:['วันจบ','enddate'],house_no:['บ้านเลขที่','แปลง','unit','plot'],address:['ที่อยู่','address'],lat:['lat','latitude'],lng:['lng','lon','longitude'],start_time:['เวลา','time'],occupied:['ผู้อยู่อาศัย','occupied']}[k]||[])].map(norm);
    const h=headers.find(x=>keys.includes(norm(x)))||headers.find(x=>keys.some(kk=>kk.length>2&&norm(x).includes(kk)));if(h)m[k]=h});return m}
const toYMD=v=>{if(v instanceof Date)return ymd(v);const s=String(v||'').trim();let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);if(m)return m[1]+'-'+z(m[2])+'-'+z(m[3]);
  m=s.match(/^(\d{1,2})[/.-](\d{1,2})[/.-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;if(y>2400)y-=543;return y+'-'+z(m[2])+'-'+z(m[1])}return s};
function SPlan(){useStore();const co=S.co&&S.co!=='all'?S.co:myCos()[0];const fields=sett('po_fields',co)||[];const [t,setT]=useState('list');const [raw,setRaw]=useState(null);const [map,setMap]=useState({});const [res,setRes]=useState(null);const [from,setFrom]=useState(addDays(today(),-7));
  const pick=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;const X=await loadScript(XLSX_URL,'XLSX');
    const wb=X.read(await f.arrayBuffer(),{cellDates:true});const rows=X.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:true});const headers=Object.keys(rows[0]||{});
    setRaw({rows,headers,name:f.name});setMap(guessMap(headers,fields,sett('po_mapping',co)));setRes(null)};
  const mapped=raw?raw.rows.map(r=>{const o={};fields.forEach(([k])=>{const h=map[k];if(h!=null&&h!=='')o[k]=r[h]});['start_date','end_date'].forEach(k=>{if(o[k]!=null)o[k]=toYMD(o[k])});
    if(o.start_time instanceof Date)o.start_time=z(o.start_time.getHours())+':'+z(o.start_time.getMinutes());Object.keys(o).forEach(k=>{if(o[k]!=null)o[k]=String(o[k]).trim()});return o}).filter(r=>r.po_no):[];
  const missing=fields.filter(([k,,req])=>req&&!map[k]).map(x=>x[1]);
  const tpl=async()=>{const X=await loadScript(XLSX_URL,'XLSX');const ws=X.utils.aoa_to_sheet([fields.map(c=>c[1]),['PO-0001',S.projects.find(p=>p.scg_company_id===co)?.name||'ม.ตัวอย่าง',S.links.find(l=>l.scg_company_id===co)?.vendor_code||'V-0001',S.jobTypes.find(x=>x.scg_company_id===co)?.name||'',today(),addDays(today(),2),'08:00','88/12','','','','Y']]);
    const wb=X.utils.book_new();X.utils.book_append_sheet(wb,ws,'PO');X.writeFile(wb,'SafeStart-PO-template.xlsx')};
  const list=visJobs().filter(j=>j.end_date>=from).sort((a,b)=>a.start_date.localeCompare(b.start_date));
  return html`<div className="col"><${Tabs} v=${t} set=${setT} opts=${[['list','รายการงาน',list.length,'cal'],...(canImport()?[['imp','นำเข้า PO จาก Excel',null,'upload']]:[])]}/>
    ${t==='imp'?html`<${Card} pad=${true} className="col"><div className="row"><label className="btn primary"><${Ic} n="upload"/>เลือกไฟล์ Excel/CSV<input type="file" accept=".xlsx,.xls,.csv" hidden onChange=${pick}/></label><${Btn} icon="download" onClick=${tpl}>Template กลาง</${Btn}>${S.co==='all'||myCos().length>1?html`<span className="sm muted">นำเข้าให้: <b>${coName(co)}</b></span>`:null}</div>
      <div className="sm muted">ใช้ไฟล์ PO รูปแบบเดิมของแต่ละบริษัทได้ · จับคู่คอลัมน์ครั้งแรก ระบบจำไว้ใช้ครั้งต่อไป · โครงการใหม่สร้างให้อัตโนมัติ (ใส่ IC และโรงพยาบาลในตั้งค่าภายหลัง) · เลข PO เดิมจะอัปเดตข้อมูล</div>
      ${raw?html`<div className="sm">ไฟล์ <b>${raw.name}</b> · ${raw.rows.length} แถว</div>
        <div className="mapgrid">${fields.map(([k,l,req])=>html`<${Field} key=${k} label=${l+(req?' *':'')}><${Sel} v=${map[k]||''} set=${v=>setMap(o=>({...o,[k]:v}))} opts=${[['','— ไม่ใช้ —'],...raw.headers.map(h=>[h,h])]}/></${Field}>`)}</div>
        ${missing.length?html`<${Banner} kind="warn">ยังไม่ได้เลือกคอลัมน์: ${missing.join(', ')}</${Banner}>`:null}
        <div className="tbl"><table><thead><tr>${['po_no','project','contractor','job_types','house_no','start_date','end_date'].map(k=>html`<th key=${k}>${(fields.find(c=>c[0]===k)||[k,k])[1]}</th>`)}</tr></thead><tbody>${mapped.slice(0,30).map((r,i)=>html`<tr key=${i}>${['po_no','project','contractor','job_types','house_no','start_date','end_date'].map(k=>html`<td key=${k} className="sm">${r[k]}</td>`)}</tr>`)}</tbody></table></div>
        <div className="row"><${Btn} kind="go" disabled=${!!missing.length||!mapped.length} onClick=${async()=>{const r=await act(()=>rpc('import_jobs',{p_co:co,p_rows:mapped}));if(r){setRes(r);run(()=>rpc('save_po_mapping',{p_co:co,p_map:map}));UI.toast('นำเข้า '+r.imported+' งาน'+(r.new_projects?' · โครงการใหม่ '+r.new_projects:'')+(r.errors.length?' · ผิดพลาด '+r.errors.length+' แถว':''))}}}>นำเข้า ${mapped.length} แถว</${Btn}></div>`:null}
      ${res&&res.errors.length?html`<${Banner} kind="warn"><b>แถวที่นำเข้าไม่ได้</b>${res.errors.map(e=>html`<div key=${e.row} className="sm">แถว ${e.row+1} (${e.po_no||'-'}): ${e.errors.join(', ')}</div>`)}</${Banner}>`:null}</${Card}>`
    :html`<div className="row"><span className="sm muted">ตั้งแต่</span><${Inp} type="date" v=${from} set=${setFrom}/></div><div className="card"><div className="tbl"><table><thead><tr><th>PO</th><th>บ้าน</th><th>โครงการ</th><th>ผู้รับเหมา</th><th>วันที่</th><th>ความเสี่ยง</th><th>สถานะ</th></tr></thead>
      <tbody>${list.map(j=>{const s=jobState(j);return html`<tr key=${j.id} className="click" onClick=${()=>UI.open(html`<${JobSheet} id=${j.id}/>`,j.po_no)}><td className="num sm">${j.po_no}</td><td>${j.house_no||'–'}</td><td className="sm">${projOf(j.project_id)?.name||''}${projOf(j.project_id)?.auto_created&&!projOf(j.project_id)?.ic_id?html` <${Chip} c="warn" t="ยังไม่มี IC"/>`:null}</td><td className="sm">${ctrName(j.contractor_id)}</td><td className="sm">${thDS(j.start_date)}–${thDS(j.end_date)}</td><td><${Chip} c=${RISK[j.risk][0]} t=${RISK[j.risk][1]}/></td><td><${Chip} c=${s[0]} t=${s[1]}/></td></tr>`})}</tbody></table></div></div>`}
  </div>`}

/* ---------- ผู้รับเหมา ---------- */
const CO_ST={pending:['warn','รออนุมัติ'],approved:['go','อนุมัติให้รับงาน'],suspended:['stop','ถูกพัก']};
function SContractors(){useStore();const canEdit=['purchasing','safety_admin'].includes(ME.role);const co=S.co&&S.co!=='all'?S.co:myCos()[0];
  const rows=S.contractors.map(c=>[c,ctrLink(c.id,co)]).filter(([,l])=>l);
  return html`<div className="col">${canEdit?html`<${ContractorSearch} co=${co}/>`:null}
    <div className="card"><div className="tbl"><table><thead><tr><th>บริษัท</th><th>รหัส Vendor</th><th>สถานะ (${coShort(co)})</th><th>เอกสาร</th><th>ช่างที่อนุมัติ</th><th>งานวันนี้</th><th>Flag</th></tr></thead><tbody>
    ${rows.map(([c,l])=>{const docs=S.docs.filter(d=>d.contractor_id===c.id);const expd=docs.some(d=>d.expires_on&&d.expires_on<today());const fl=S.flags.filter(f=>f.contractor_id===c.id).length;
      return html`<tr key=${c.id} className="click" onClick=${()=>UI.open(html`<${CompanySheet} id=${c.id}/>`,c.name)}><td>${c.name}<div className="xs muted num">${c.tax_id||''}</div></td><td className="num sm">${l.vendor_code||'–'}</td><td><${Chip} c=${CO_ST[l.status][0]} t=${CO_ST[l.status][1]}/></td>
      <td>${expd?html`<${Chip} c="stop" t="มีหมดอายุ"/>`:html`<span className="sm">${docs.length} ไฟล์</span>`}</td>
      <td className="sm">${S.wlinks.filter(x=>x.scg_company_id===co&&x.status==='approved'&&workerOf(x.worker_id)?.contractor_id===c.id).length}/${S.workers.filter(w=>w.contractor_id===c.id).length}</td><td className="sm">${S.jobs.filter(j=>j.contractor_id===c.id&&isToday(j)&&j.scg_company_id===co).length}</td><td>${fl?html`<${Chip} c="stop" t=${'LSR '+fl}/>`:'–'}</td></tr>`})}</tbody></table></div></div></div>`}
function ContractorSearch({co}){const [tax,setTax]=useState('');const [r,setR]=useState(undefined);const [f,setF]=useState({name:'',contact:'',phone:'',email:'',vendor:'',admin:''});const set=k=>v=>setF(o=>({...o,[k]:v}));
  return html`<${Card} pad=${true} className="col tight"><b>ลงทะเบียนผู้รับเหมา · ${coName(co)}</b><div className="row"><${Inp} v=${tax} set=${v=>{setTax(v.replace(/\D/g,''));setR(undefined)}} mode="numeric" max=${13} ph="เลขผู้เสียภาษี 13 หลัก"/><${Btn} icon="search" disabled=${tax.length!==13} onClick=${async()=>{const x=await run(()=>rpc('find_contractor',{p_tax:tax}));setR(x===true?null:x||null)}}>ค้นหา</${Btn}></div>
    ${r===null?html`<div className="sm">ยังไม่มีในระบบ · สร้างใหม่</div><div className="fgrid"><${Inp} v=${f.name} set=${set('name')} ph="ชื่อบริษัท"/><${Inp} v=${f.contact} set=${set('contact')} ph="ผู้ติดต่อ"/><${Inp} v=${f.phone} set=${set('phone')} ph="เบอร์โทร"/><${Inp} v=${f.email} set=${set('email')} ph="อีเมลบริษัท"/><${Inp} v=${f.vendor} set=${set('vendor')} ph="รหัส Vendor (ที่ใช้ในไฟล์ PO)"/><${Inp} v=${f.admin} set=${set('admin')} type="email" ph="อีเมลผู้ดูแลบริษัท (เชิญเข้าแอป)"/></div>
      <${Btn} kind="primary" disabled=${!f.name.trim()} onClick=${async()=>{const id=await act(()=>rpc('register_contractor',{p_co:co,p_name:f.name,p_tax:tax,p_contact:f.contact,p_phone:f.phone,p_email:f.email,p_vendor_code:f.vendor,p_approve:true}),'ลงทะเบียนและอนุมัติแล้ว');
        if(id&&f.admin)await act(()=>rpc('invite_user',{p_email:f.admin,p_name:f.contact,p_role:'contractor_admin',p_cos:[],p_contractor:id}),'เชิญผู้ดูแลบริษัทแล้ว');setR(undefined);setTax('')}}>ลงทะเบียนและอนุมัติ</${Btn}>`:null}
    ${r?html`<div className="card pad col tight"><b>${r.name}</b><div className="sm muted">${r.contact_name||''} ${r.contact_phone||''} · อยู่ในทะเบียน: ${r.linked.map(x=>x.company+' ('+x.status+')').join(', ')||'–'}</div>
      ${r.flags.length?html`<${Banner} kind="stop"><b>Flag กฎพิทักษ์ชีวิต 12 เดือน (แจ้งให้ทราบ · ตัดสินใจเอง)</b>${r.flags.map((x,i)=>html`<div key=${i} className="sm">ข้อ ${x.rule} · ${thD(x.date)} · ${x.penalty} · ${x.company}${x.worker?' · '+x.worker:''}</div>`)}</${Banner}>`:null}
      <div className="row"><${Inp} v=${f.vendor} set=${set('vendor')} ph="รหัส Vendor ของบริษัทเรา"/><${Btn} kind="primary" onClick=${async()=>{if(await act(()=>rpc('register_contractor',{p_co:co,p_name:r.name,p_tax:tax,p_contact:null,p_phone:null,p_email:null,p_vendor_code:f.vendor,p_approve:true}),'เพิ่มเข้าทะเบียน '+coShort(co)+' แล้ว'))setR(undefined)}}>เพิ่มเข้าทะเบียนบริษัทเรา</${Btn}></div></div>`:null}</${Card}>`}
function CompanySheet({id}){useStore();const c=byId(S.contractors,id);if(!c)return null;const co=S.co&&S.co!=='all'?S.co:myCos()[0];const l=ctrLink(id,co)||{};const canEdit=['purchasing','safety_admin'].includes(ME.role);
  const [st,setSt]=useState(l.status||'pending');const [vc,setVc]=useState(l.vendor_code||'');const [note,setNote]=useState('');const ws=S.workers.filter(w=>w.contractor_id===id);const docs=S.docs.filter(d=>d.contractor_id===id);const DT=sett('doc_types',null)||{};const fl=S.flags.filter(f=>f.contractor_id===id);
  return html`<${Sheet} size="wide" title=${c.name} sub=${'เลขภาษี '+(c.tax_id||'–')+' · '+(c.contact_name||'')+' '+(c.contact_phone||'')}>
    ${fl.length?html`<${Banner} kind="stop"><b>Flag กฎพิทักษ์ชีวิต</b>${fl.map(f=>html`<div key=${f.id} className="sm">ข้อ ${f.rule} · ${thD(f.occurred_on)} · ${f.penalty} · ${coName(f.scg_company_id)}${f.worker_id?' · '+workerName(f.worker_id):''}</div>`)}</${Banner}>`:null}
    <div className="card pad col tight"><div className="between"><b>สถานะกับ ${coName(co)}</b><${Chip} c=${CO_ST[l.status||'pending'][0]} t=${CO_ST[l.status||'pending'][1]}/></div>
      ${canEdit?html`<div className="row"><${Seg} v=${st} set=${setSt} opts=${[['pending','รออนุมัติ'],['approved','อนุมัติ'],['suspended','พักรับงาน']]}/><${Inp} v=${vc} set=${setVc} ph="รหัส Vendor"/></div><${Inp} v=${note} set=${setNote} ph="หมายเหตุ"/>
        <${Btn} kind="primary" onClick=${()=>act(()=>rpc('decide_contractor',{p_co:co,p_contractor:id,p_status:st,p_vendor_code:vc,p_note:note||null}),'บันทึกแล้ว')}>บันทึกสถานะ</${Btn}>`:null}
      <div className="xs muted">จป.: ${c.safety_officer||'–'} · ${c.email||''}</div></div>
    <div className="eyebrow">เอกสารบริษัท</div><div className="col tight">${Object.entries(DT).filter(([k])=>k!=='other').map(([k,lb])=>{const d=docs.filter(x=>x.doc_type===k).sort((a,b)=>(b.expires_on||'9999').localeCompare(a.expires_on||'9999'))[0];
      return html`<div key=${k} className="between sm"><span>${lb}</span><span className="row">${d?html`<${Img} path=${d.file_path}/>`:null}<${Chip} c=${!d||(d.expires_on&&d.expires_on<today())?'stop':d.expires_on&&d.expires_on<addDays(today(),30)?'warn':'go'} t=${d?(d.expires_on?'หมดอายุ '+thD(d.expires_on):'ไม่มีวันหมดอายุ'):'ยังไม่ส่ง'}/></span></div>`})}</div>
    ${canEdit?html`<${InviteBox} roles=${[['contractor_admin','ผู้ดูแลบริษัท']]} contractor=${id} label="เชิญผู้ดูแลบริษัทผู้รับเหมา"/>`:null}
    <div className="eyebrow">ช่าง ${ws.length} คน</div><div className="list card">${ws.map(w=>{const lk=linkOf(w.id,co);return html`<button key=${w.id} className="li" onClick=${()=>UI.open(html`<${WorkerSheet} id=${w.id}/>`,w.full_name)}><${Avatar} n=${w.nickname||w.full_name}/><div className="grow"><div className="t">${w.full_name}</div><div className="s">${w.position||''} · ${NAT[w.nationality]}</div></div>${lk?html`<${Chip} c=${W_ST[wStatus(w,co)][0]} t=${W_ST[wStatus(w,co)][1]}/>`:html`<${Chip} t="ไม่ได้ขอ"/>`}</button>`})}</div>
  </${Sheet}>`}

/* ---------- Findings + เหตุการณ์ ---------- */
const INC_NAME={sos:'SOS',injury:'บาดเจ็บ',property:'ทรัพย์สินเสียหาย',near_miss:'Near miss',unsafe_condition:'สภาพไม่ปลอดภัย',unsafe_act:'พฤติกรรมไม่ปลอดภัย'};
function IncidentRow({i}){const j=i.job_id&&byId(S.jobs,i.job_id);return html`<button className="li" onClick=${()=>UI.open(html`<${IncidentView} id=${i.id}/>`,INC_NAME[i.kind])}><span className=${'ic-circle '+(['sos','injury'].includes(i.kind)?'stop':'warn')}><${Ic} n=${i.kind==='sos'?'sos':'warn'}/></span><div className="grow"><div className="t">${INC_NAME[i.kind]}${j?' · '+j.po_no:''}</div><div className="s">${i.description||''} · ${ago(i.created_at)}</div></div><${Chip} c=${i.status==='new'?'stop':i.status==='acknowledged'?'warn':'go'} t=${i.status==='new'?'ใหม่':i.status==='acknowledged'?'รับเรื่องแล้ว':'ปิดแล้ว'}/></button>`}
function IncidentView({id}){useStore();const i=byId(S.incidents,id);const [n,setN]=useState('');if(!i)return null;const j=i.job_id&&byId(S.jobs,i.job_id);
  return html`<${Sheet} title=${INC_NAME[i.kind]} sub=${(j?j.po_no+' · '+(j.house_no||'')+' · ':'')+ctrName(i.contractor_id)+' · '+thT(i.created_at)} foot=${isSCG()&&i.status!=='closed'?html`<div className="row" style=${{width:'100%'}}>${i.status==='new'?html`<${Btn} onClick=${()=>act(()=>rpc('handle_incident',{p_id:id,p_status:'acknowledged',p_note:n||null}),'รับเรื่องแล้ว')}>รับเรื่อง</${Btn}>`:null}<div className="grow"></div><${Btn} kind="go" onClick=${()=>act(()=>rpc('handle_incident',{p_id:id,p_status:'closed',p_note:n||null}),'ปิดเรื่องแล้ว')}>ปิดเรื่อง</${Btn}></div>`:null}>
    <div className="sm">${i.description||'–'}</div><div className="row">${(i.photos||[]).map(p=>html`<${Img} key=${p} path=${p} cls="thumb lg"/>`)}</div>
    ${i.lat?html`<a className="btn" target="_blank" rel="noopener" href=${'https://maps.google.com/?q='+i.lat+','+i.lng}><${Ic} n="map"/>ตำแหน่งที่แจ้ง</a>`:null}
    <div className="xs muted">แจ้งโดย ${profName(i.reported_by)}${i.handled_at?' · '+profName(i.handled_by)+' '+thT(i.handled_at)+(i.handle_note?': '+i.handle_note:''):''}</div>
    ${isSCG()&&i.status!=='closed'?html`<${Field} label="บันทึกการดำเนินการ"><${Txt} v=${n} set=${setN} ph="เช่น ตรวจหน้างานแล้ว ให้เปลี่ยนบันได"/></${Field}><div className="xs muted">การสอบสวนเต็มรูปแบบ (5 Why · ระดับ · มาตรการ) อยู่ในรอบถัดไป</div>`:null}</${Sheet}>`}
function SFindings(){useStore();const [t,setT]=useState('f');const [f,setF]=useState('active');const list=S.findings.filter(x=>inCo(x.scg_company_id)&&(f==='active'?['open','fixed'].includes(x.status):true));const inc=S.incidents.filter(i=>inCo(i.scg_company_id));
  return html`<div className="col"><div className="between"><${Tabs} v=${t} set=${setT} opts=${[['f','Findings',list.length,'flag'],['i','เหตุการณ์',inc.filter(i=>i.status!=='closed').length,'warn']]}/><${Btn} kind="danger" icon="warn" onClick=${()=>UI.open(html`<${IncidentSheet}/>`,'แจ้งเหตุ')}>แจ้งเหตุ</${Btn}></div>
    ${t==='f'?html`<${Seg} v=${f} set=${setF} opts=${[['active','ยังไม่ปิด'],['all','ทั้งหมด 90 วัน']]}/><${Card}>${list.length?html`<div className="list">${list.map(x=>html`<${FindingRow} key=${x.id} f=${x}/>`)}</div>`:html`<${Empty} icon="ok" t="ไม่มี finding"/>`}</${Card}>`
      :html`<${Card}>${inc.length?html`<div className="list">${inc.map(i=>html`<${IncidentRow} key=${i.id} i=${i}/>`)}</div>`:html`<${Empty} icon="ok" t="ยังไม่มีการแจ้งเหตุ"/>`}</${Card}>`}</div>`}

/* ---------- สแกนบัตรผ่าน (ฝั่ง SCG) ---------- */
function SScan(){const [r,setR]=useState(null);const [tok,setTok]=useState('');const [on,setOn]=useState(false);const vid=useRef(null);const stream=useRef(null);
  const check=async t=>{const m=String(t).match(/pass-([0-9a-f]+)/);const k=m?m[1]:String(t).trim();if(!k)return;const x=await run(()=>rpc('verify_pass',{p_token:k}));if(x)setR(x);stop()};
  const stop=()=>{try{stream.current&&stream.current.getTracks().forEach(t=>t.stop())}catch(e){}setOn(false)};
  const start=async()=>{setR(null);try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});setOn(true);setTimeout(async()=>{vid.current.srcObject=stream.current;await vid.current.play();loop()},50)}catch(e){UI.toast('เปิดกล้องไม่ได้ ใส่รหัสแทน')}};
  const loop=async()=>{const det='BarcodeDetector' in window?new BarcodeDetector({formats:['qr_code']}):null;let jsqr=null;if(!det)jsqr=await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jsQR/1.4.0/jsQR.min.js','jsQR').catch(()=>null);
    const c=document.createElement('canvas');const tick=async()=>{if(!stream.current||!vid.current||vid.current.readyState<2){if(stream.current)requestAnimationFrame(tick);return}
      try{if(det){const b=await det.detect(vid.current);if(b[0])return check(b[0].rawValue)}else if(jsqr){c.width=vid.current.videoWidth;c.height=vid.current.videoHeight;const g5=c.getContext('2d');g5.drawImage(vid.current,0,0);const d=g5.getImageData(0,0,c.width,c.height);const q3=jsqr(d.data,c.width,c.height);if(q3)return check(q3.data)}}catch(e){}
      if(stream.current&&stream.current.active)requestAnimationFrame(tick)};tick()};
  useEffect(()=>stop,[]);
  return html`<div className="col" style=${{maxWidth:640}}>
    <${Card} pad=${true} className="col"><div className="row">${on?html`<${Btn} onClick=${stop}>ปิดกล้อง</${Btn}>`:html`<${Btn} kind="primary" big=${true} icon="scan" onClick=${start}>เปิดกล้องสแกน QR</${Btn}>`}</div>
      ${on?html`<video ref=${vid} className="scanvid" playsInline muted></video>`:null}
      <div className="row"><${Inp} v=${tok} set=${setTok} ph="หรือวางลิงก์/รหัสบัตรผ่าน"/><${Btn} disabled=${!tok} onClick=${()=>check(tok)}>ตรวจ</${Btn}></div></${Card}>
    ${r?html`<${PassResult} r=${r}/>`:null}</div>`}
function PassResult({r}){return html`<div className=${cx('pass2',r.valid?(r.stage==='setup'?'orange':'green'):'red')}>
  <h1>${r.valid?(r.stage==='setup'?'ใช้ได้ · ขั้นติดตั้ง':'ใช้ได้ · ทำงาน'):'ใช้ไม่ได้'}</h1>
  <div className="sm">${!r.found?'ไม่พบบัตรนี้':r.stopped?'งานถูกสั่งหยุด':r.voided?'ถูกยกเลิก':r.closed?'ปิดงานของวันนั้นแล้ว':!r.valid?'ไม่ใช่บัตรของวันนี้':(r.company||'')}</div>
  ${r.workers?html`<div className="ppl sm"><div><b>${r.project||''} · ${r.house_no||''}</b> · ${r.po_no||''}</div><div>${r.contractor||''} · check-in ${r.time||''} น.</div>
    ${r.workers.map((w,i)=>html`<div key=${i} className="between"><span>${w.name}</span><span>${w.setup&&r.stage==='setup'?'ติดตั้ง':w.wah?'ขึ้นที่สูง':'งานพื้น'}</span></div>`)}</div>
    <div className="xs" style=${{opacity:.9}}>เทียบรายชื่อกับคนที่อยู่หน้างานจริง · Line Walk แบบเต็มอยู่รอบถัดไป</div>
    ${r.job_id?html`<${Btn} onClick=${()=>UI.open(html`<${JobSheet} id=${r.job_id}/>`,r.po_no)}>เปิดรายละเอียดงาน</${Btn}>`:null}`:html`<div className="xs">เข้าสู่ระบบด้วยบัญชี SCG เพื่อดูรายละเอียด</div>`}</div>`}

/* ---------- ตั้งค่า (Safety Admin ของแต่ละบริษัท) ---------- */
function SSettings(){useStore();const [t,setT]=useState('proj');const co=S.co&&S.co!=='all'?S.co:myCos()[0];
  return html`<div className="col"><${Tabs} v=${t} set=${setT} opts=${[['proj','โครงการ',null,'home'],['grp','กลุ่มงาน',null,'building'],['jt','ประเภทงาน',null,'tool'],['users','ผู้ใช้',null,'user'],['rules','กติกา/อากาศ',null,'cog'],['cl','เช็กลิสต์',null,'check'],...(ME.is_owner?[['own','บริษัท SCG',null,'shield']]:[])]}/>
    <div className="sm muted">ตั้งค่าของ <b>${coName(co)}</b> · บริษัทอื่นในกลุ่มไม่เห็นและไม่ได้รับผล</div>
    ${t==='proj'?html`<div className="row"><${Btn} kind="primary" icon="plus" onClick=${()=>UI.open(html`<${ProjectSheet} co=${co}/>`,'เพิ่มโครงการ')}>เพิ่มโครงการ</${Btn}></div><div className="card"><div className="tbl"><table><thead><tr><th>โครงการ</th><th>กลุ่มงาน</th><th>IC</th><th>โรงพยาบาล</th></tr></thead><tbody>${S.projects.filter(p=>p.scg_company_id===co).map(p=>html`<tr key=${p.id} className="click" onClick=${()=>UI.open(html`<${ProjectSheet} id=${p.id} co=${co}/>`,p.name)}><td>${p.name}${p.auto_created?html` <${Chip} t="จาก PO"/>`:null}</td><td className="sm">${grpName(p.group_id)}</td><td className="sm">${p.ic_id?profName(p.ic_id):html`<span style=${{color:'var(--warn)'}}>ยังไม่กำหนด</span>`}${p.backup_ic_id?' / '+profName(p.backup_ic_id):''}</td><td className="sm">${p.hospital||html`<span style=${{color:'var(--warn)'}}>ยังไม่ตั้ง</span>`}</td></tr>`)}</tbody></table></div></div>`:null}
    ${t==='grp'?html`<${NameList} table="install_groups" co=${co} title="กลุ่มงานติดตั้ง" rows=${S.groups.filter(x=>x.scg_company_id===co)}/>`:null}
    ${t==='jt'?html`<${JobTypes} co=${co}/>`:null}
    ${t==='users'?html`<${Users} co=${co}/>`:null}
    ${t==='rules'?html`<${Rules} co=${co}/>`:null}
    ${t==='cl'?html`<${JsonSetting} co=${co} k="checklist" hint="หมวดมี when = all / occupied / ladder / scaffold / wah / electric / hot / confined / lifting / excavation / chemical · ข้อมี code, text, t (คำแปล my/km/lo), crit, na, lsr, ill (ภาพ), setup (ส่งรูปในขั้นบัตรส้ม)"/><${JsonSetting} co=${co} k="closeout"/><${JsonSetting} co=${co} k="toolbox"/><${JsonSetting} co=${co} k="hazard_certs"/><${JsonSetting} co=${co} k="setup_methods"/>`:null}
    ${t==='own'?html`<${OwnerCompanies}/>`:null}</div>`}
function ProjectSheet({id,co}){const p=id?byId(S.projects,id):{};const [f,setF]=useState({name:p.name||'',group_id:p.group_id||'',ic_id:p.ic_id||'',backup_ic_id:p.backup_ic_id||'',hospital:p.hospital||'',hospital_phone:p.hospital_phone||'',hospital_km:p.hospital_km??'',lat:p.lat??'',lng:p.lng??''});
  const set=k=>v=>setF(o=>({...o,[k]:v}));const ics=S.profiles.filter(x=>['installation_consultant','ic_qc_manager','safety_admin'].includes(x.role)&&(x.scg_company_ids||[]).includes(co)).map(x=>[x.id,(x.full_name||x.email)+' · '+ROLE_NAME[x.role]]);
  const row={...f,scg_company_id:co,group_id:f.group_id||null,ic_id:f.ic_id||null,backup_ic_id:f.backup_ic_id||null,hospital_km:f.hospital_km===''?null:+f.hospital_km,lat:f.lat===''?null:+f.lat,lng:f.lng===''?null:+f.lng};
  return html`<${Sheet} title=${id?'แก้โครงการ':'เพิ่มโครงการ'} foot=${html`<${Btn} kind="primary" block=${true} disabled=${!f.name.trim()} onClick=${()=>act(async()=>{const r=id?await sb.from('projects').update(row).eq('id',id):await sb.from('projects').insert(row);if(r.error)throw r.error;UI.close()},'บันทึกแล้ว')}>บันทึก</${Btn}>`}>
    <${Field} label="ชื่อโครงการ/หมู่บ้าน"><${Inp} v=${f.name} set=${set('name')}/></${Field}>
    <div className="fgrid"><${Field} label="กลุ่มงานหลัก"><${Sel} v=${f.group_id} set=${set('group_id')} opts=${[['','–'],...S.groups.filter(x=>x.scg_company_id===co).map(x=>[x.id,x.name])]}/></${Field}>
      <${Field} label="IC (ผู้อนุมัติงานเสี่ยงสูง)"><${Sel} v=${f.ic_id} set=${set('ic_id')} opts=${[['','ยังไม่กำหนด (ส่ง IC&QC Mgr/Safety)'],...ics]}/></${Field}><${Field} label="IC สำรอง"><${Sel} v=${f.backup_ic_id} set=${set('backup_ic_id')} opts=${[['','–'],...ics]}/></${Field}>
      <${Field} label="โรงพยาบาลใกล้ที่สุด"><${Inp} v=${f.hospital} set=${set('hospital')}/></${Field}><${Field} label="เบอร์โรงพยาบาล"><${Inp} v=${f.hospital_phone} set=${set('hospital_phone')}/></${Field}><${Field} label="ระยะทาง (กม.)"><${Inp} v=${f.hospital_km} set=${set('hospital_km')} mode="decimal"/></${Field}>
      <${Field} label="ละติจูดโครงการ"><${Inp} v=${f.lat} set=${set('lat')} mode="decimal"/></${Field}><${Field} label="ลองจิจูด"><${Inp} v=${f.lng} set=${set('lng')} mode="decimal"/></${Field}></div></${Sheet}>`}
function NameList({table,title,rows,co}){const [n,setN]=useState('');return html`<${Card}><${CardH} title=${title}/><div className="card-b col tight">${rows.map(r=>html`<div key=${r.id} className="sm">${r.name}</div>`)}
  <div className="row"><${Inp} v=${n} set=${setN} ph="เพิ่มใหม่"/><${Btn} small=${true} disabled=${!n.trim()} onClick=${async()=>{if(await act(async()=>{const {error}=await sb.from(table).insert({name:n.trim(),scg_company_id:co,sort:rows.length});if(error)throw error},'เพิ่มแล้ว'))setN('')}}>เพิ่ม</${Btn}></div></div></${Card}>`}
function JobTypes({co}){useStore();const [n,setN]=useState('');const [gp,setGp]=useState('');const jts=S.jobTypes.filter(x=>x.scg_company_id===co);
  const toggle=(jt,h)=>act(async()=>{const hs=jt.hazards.includes(h)?jt.hazards.filter(x=>x!==h):[...jt.hazards,h];const {error}=await sb.from('job_types').update({hazards:hs}).eq('id',jt.id);if(error)throw error});
  return html`<div className="col"><${Card} pad=${true} className="row"><${Inp} v=${n} set=${setN} ph="ประเภทงานใหม่"/><${Sel} v=${gp} set=${setGp} opts=${[['','กลุ่มงาน'],...S.groups.filter(x=>x.scg_company_id===co).map(x=>[x.id,x.name])]}/><${Btn} kind="dark" disabled=${!n.trim()} onClick=${async()=>{if(await act(async()=>{const {error}=await sb.from('job_types').insert({name:n.trim(),group_id:gp||null,scg_company_id:co});if(error)throw error},'เพิ่มแล้ว'))setN('')}}>เพิ่ม</${Btn}></${Card}>
    <div className="card"><div className="tbl"><table><thead><tr><th>ประเภทงาน</th><th>กลุ่มงาน</th>${HZ_ORDER.map(k=>html`<th key=${k} className="xs" title=${hzName(k)}><${Ic} n=${k} s=${18}/><div>${hzName(k)}</div></th>`)}</tr></thead><tbody>${jts.map(jt=>html`<tr key=${jt.id}><td>${jt.name}</td><td className="sm">${grpName(jt.group_id)}</td>${HZ_ORDER.map(k=>html`<td key=${k}><input type="checkbox" aria-label=${jt.name+' '+hzName(k)} checked=${jt.hazards.includes(k)} onChange=${()=>toggle(jt,k)}/></td>`)}</tr>`)}</tbody></table></div></div>
    <div className="sm muted">เสี่ยงสูง = ที่สูง/ไฟฟ้า/ประกายไฟ/ในฝ้า (IC อนุมัติ) · เสี่ยงกลาง = ยก/ขุด/สารเคมี (ผู้ดูแลบริษัทผู้รับเหมาอนุมัติ IC ได้แจ้ง) · ไม่มี = อนุมัติอัตโนมัติ</div></div>`}
function Users({co}){useStore();const users=S.profiles.filter(p=>(p.scg_company_ids||[]).includes(co)&&SCG_ROLES.includes(p.role));const pend=S.invites.filter(i=>(i.scg_company_ids||[]).includes(co)&&!S.profiles.some(p=>p.email.toLowerCase()===i.email.toLowerCase()));
  return html`<div className="col"><${InviteBox} roles=${SCG_ROLES.map(r=>[r,ROLE_NAME[r]])} cos=${[co]} label=${'เชิญผู้ใช้ SCG · '+coName(co)}/>
    <div className="card"><div className="tbl"><table><thead><tr><th>ชื่อ</th><th>อีเมล</th><th>บทบาท</th><th>LINE</th><th>ใช้งาน</th></tr></thead><tbody>
      ${users.map(p=>html`<tr key=${p.id}><td>${p.full_name||'–'}</td><td className="sm">${p.email}</td><td>${p.id===ME.id?ROLE_NAME[p.role]:html`<${Sel} v=${p.role} set=${v=>act(()=>rpc('set_user',{p_id:p.id,p_role:v,p_active:p.active}),'บันทึกแล้ว')} opts=${SCG_ROLES.map(r=>[r,ROLE_NAME[r]])}/>`}</td>
        <td>${p.line_user_id?html`<${Chip} c="go" t="ผูกแล้ว"/>`:html`<${Chip} t="–"/>`}</td><td>${p.id===ME.id?'–':html`<input type="checkbox" aria-label="ใช้งาน" checked=${p.active} onChange=${e=>act(()=>rpc('set_user',{p_id:p.id,p_role:p.role,p_active:e.target.checked}),'บันทึกแล้ว')}/>`}</td></tr>`)}
      ${pend.map(i=>html`<tr key=${i.email}><td>${i.full_name||'–'}</td><td className="sm">${i.email}</td><td className="sm">${ROLE_NAME[i.role]}</td><td colspan="2"><${Chip} c="warn" t="รอเข้าระบบครั้งแรก"/></td></tr>`)}</tbody></table></div></div></div>`}
function Rules({co}){useStore();const [sla,setSla]=useState(sett('sla',co)||{});const [r,setR]=useState(sett('rules',co)||{});const [wx,setWx]=useState(sett('weather',co)||{gust:[25,40,55],rain_prob:[40,70],heat:[27,33,42,52]});
  const save=()=>act(async()=>{for(const [k,v] of [['sla',sla],['rules',r],['weather',wx]]){const {error}=await sb.from('settings').upsert({scg_company_id:co,key:k,value:v},{onConflict:'scg_company_id,key'});if(error)throw error}},'บันทึกกติกาแล้ว');
  const F=(o,set,k,l,type)=>html`<${Field} key=${k} label=${l}><${Inp} type=${type||'text'} v=${o[k]} set=${v=>set(x=>({...x,[k]:type==='number'?+v:v}))}/></${Field}>`;
  const A=(k,i,l)=>html`<${Field} key=${k+i} label=${l}><${Inp} type="number" v=${(wx[k]||[])[i]} set=${v=>setWx(x=>{const a=[...(x[k]||[])];a[i]=+v;return{...x,[k]:a}})}/></${Field}>`;
  return html`<${Card} pad=${true} className="col"><div className="eyebrow">เวลาและ SLA</div><div className="fgrid">${F(sla,setSla,'ack_normal_min','รับทราบเรื่องทั่วไป (นาที)','number')}${F(sla,setSla,'ack_urgent_min','รับทราบเรื่องด่วน (นาที)','number')}${F(sla,setSla,'finding_hours','แก้ finding (ชม.)','number')}
    ${F(sla,setSla,'permit_deadline','ยื่นใบอนุญาตเสี่ยงสูงก่อน (วันก่อนเข้างาน)','time')}${F(sla,setSla,'closeout_by','ปิดงานก่อน','time')}</div>
    <div className="eyebrow">Check-in</div><div className="fgrid">${F(r,setR,'radius_m','รัศมี check-in (เมตร)','number')}${F(r,setR,'late_min','นับว่าสายหลังเวลานัด (นาที)','number')}${F(r,setR,'setup_minutes','เวลาส่งรูปบัตรส้ม (นาที)','number')}</div>
    <${Check} on=${r.enforce_certs!==false} set=${v=>setR(x=>({...x,enforce_certs:v}))}>บังคับ cert ที่รับรองแล้วก่อนเลือกช่างเข้างาน</${Check}><${Check} on=${!!r.enforce_docs} set=${v=>setR(x=>({...x,enforce_docs:v}))}>พักรับงานเมื่อเอกสารบริษัทหมดอายุ</${Check}>
    <div className="eyebrow">เกณฑ์สภาพอากาศ (งานที่สูงกลางแจ้ง)</div><div className="fgrid">${A('gust',0,'ลม เฝ้าระวัง ≥')}${A('gust',1,'ลม งดยกแผ่นใหญ่ ≥')}${A('gust',2,'ลม หยุดงานที่สูง ≥')}${A('rain_prob',0,'ฝน เฝ้าระวัง ≥ %')}${A('rain_prob',1,'ฝน ระวังสูง ≥ %')}
      ${A('heat',1,'ดัชนีความร้อน เตือนภัย ≥')}${A('heat',2,'ดัชนีความร้อน อันตราย ≥')}${A('heat',3,'ดัชนีความร้อน อันตรายมาก ≥')}</div>
    <${Btn} kind="primary" onClick=${save}>บันทึก</${Btn}></${Card}>`}
function JsonSetting({k,hint,co}){useStore();const [v,setV]=useState(JSON.stringify(sett(k,co)??null,null,1));let ok=true;try{JSON.parse(v)}catch(e){ok=false}
  return html`<${Card}><${CardH} title=${k} sub=${hint}/><div className="card-b col tight"><textarea className="inp num" rows="10" value=${v} onChange=${e=>setV(e.target.value)} style=${{fontSize:12.5}}></textarea>
    ${ok?null:html`<div className="xs" style=${{color:'var(--stop)'}}>รูปแบบ JSON ไม่ถูกต้อง</div>`}<${Btn} small=${true} kind="dark" disabled=${!ok} onClick=${()=>act(async()=>{const {error}=await sb.from('settings').upsert({scg_company_id:co,key:k,value:JSON.parse(v)},{onConflict:'scg_company_id,key'});if(error)throw error},'บันทึกแล้ว')}>บันทึก ${k}</${Btn}></div></${Card}>`}
function OwnerCompanies(){useStore();const [f,setF]=useState({name:'',short:'',color:'#7A4FB3',email:'',admin:''});const set=k=>v=>setF(o=>({...o,[k]:v}));
  return html`<div className="col"><${Card}><${CardH} title="บริษัท SCG ในระบบ" sub="ผู้ดูแลระบบสร้างบริษัทและเชิญ Safety Admin คนแรก"/><div className="list">${S.companies.map(c=>html`<div key=${c.id} className="li"><span className="cobadge" style=${{'--co':c.color}}>${c.short}</span><div className="grow">${c.name}</div></div>`)}</div></${Card}>
    <${Card} pad=${true} className="col tight"><b>เพิ่มบริษัท</b><div className="fgrid"><${Inp} v=${f.name} set=${set('name')} ph="ชื่อบริษัท"/><${Inp} v=${f.short} set=${set('short')} ph="ชื่อย่อ"/><input className="inp" type="color" value=${f.color} onChange=${e=>set('color')(e.target.value)} aria-label="สีบริษัท"/>
      <${Inp} v=${f.admin} set=${set('admin')} ph="ชื่อ Safety Admin"/><${Inp} v=${f.email} set=${set('email')} type="email" ph="อีเมล Safety Admin"/></div>
      <${Btn} kind="primary" disabled=${!f.name.trim()} onClick=${()=>act(()=>rpc('owner_create_company',{p_name:f.name,p_short:f.short,p_color:f.color,p_admin_email:f.email,p_admin_name:f.admin}),'สร้างบริษัทแล้ว')}>สร้างบริษัท</${Btn}></${Card}></div>`}
